spring:
  application:
    name: ClassTrack-SpringBoot-RestAPI
  datasource:
    url: jdbc:h2:mem:classtrack
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console