
spring:
  application:
    name: Q3
  #Datasource Configuration
  datasource:
    url: jdbc:h2:mem:product
    username: sa
    password:
    driver-class-name: org.h2.Driver
  # jpa Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  # H2 Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
