spring:
  application:
    name: DemoCRUD
  datasource:
    url: jdbc:mysql://localhost:3306/DemoCrud?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  jpa:
#    database-platform: